### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by martinig** [martinig/Fitness-and-dispersal-MA#16]
@martinig 
- [x] finalize ISBE abstract
- [x] submit ISBE travel grant
- [x] create taxonomic tree with phylopic images
- [x] save the images for attribution
- [x] add GPS points to each paper
- [x] check five of each confirmation bias types for agreement
- [x] make country map with points at each location
- [x] check for mistakes in species columns
- [x] supplemental material (methods)
- [x] introduction
- [x] methods - add new stuff
- [x] results  - add new stuff
- [x] supplemental material (results)
- [x] figures (overall effect + moderators)
- [x] tables
- [x] discussion
- [x] abstract 
- [x] keywords
- [x] verify potential apparent survival papers
- [x] for Saatoglu et al. 2025: add RIS to rayyan full-text screening and extractions, add DOI and rayyanID to included/excluded csv
- [x] add Yefeng's scripts to qmd
- [x] annotate qmd
- [x] reformat MS for submission
- [x] solicit feedback from collaborators
- [x] incorporate feedback
- [x] cover letter
- [x] reviewers and editors
- [x] submit

**Comment by martinig** [comment]
@Spenser
- [x] author emails for: Spatial organization and recruitment of lynx (Lynx lynx) in a re-introduced population in the Swiss Jura Mountains
- [x] author emails for: Dispersal movements and survival rates of juvenile Mexican Spotted Owls in Northern Arizona
- [x] author emails for: Proximate and ultimate causes of dispersal in the Iberian lynx Lynx pardinus
- [x] author emails for: Emigration to new habitats by voles: The cost of dispersal paradox
- [ ] add column for whether paper stated dispersal was costly in abstract/introduction (confirmation bias)
- [x] flag which studies might be repeats of each other (e.g., Germain et al. 2017a and 2017b) - this is also included in Rayyan under "exclusion" reasons
- [ ] flag studies that use mark recapture methods (i.e., possible apparent survival)
- [ ] cross-checking records L316-328
- [x] cross-checking records L446-449
- [x] cross-checking records L458-459
- [x] cross-checking records L463-464
- [x] cross-checking records L484-489
- [x] cross-checking records L555-557
- [x] Aim 1 in rayyan mark "Correlates and consequences of breeding dispersal in a migratory songbird" as excluded
- [ ] add "label" for "overlapping population [species]" to studies that are using datasets that are have some degree of overlap for included studies only
- [ ] cross check Greenwood et al. 1979 and fill in red blanks
- [ ] cross check Pusey & Packer 1987 and fill in red blanks
- [ ] fill in red blanks for Hines 1986

**Comment by martinig** [comment]
@itchyshin 
- [x] cross-checking records (to be assigned)
- [x] quarto - table
- [x] quarto - uni-mod
- [x] quarto - mulit-mod
- [x] quarto - run
- [ ] interactions - sex * taxonomy
- [ ] interactions -sex * fitness_cleaned 
- [ ] interactions - sex * generation
- [ ] interactions - sex * dispersal_type
- [x] how to do sanity checks for proportion_method2 and percent_method2 (with SD)
- **sanity checks - d/mean **
- [x] #Krohne & Burgin 1987 (line 41) -> had to convert SE to SD using an estimated n -> we concluded this is likely SD
- [x] #Engh et al. 2002 (line 242) -> had to convert SE to SD -> we concluded this is OK
- [x] #Pärn et al. 2009 (line 301-302) -> had to convert SE to SD -> we fixed the typo (on our end)
- [x] #Cotto et al. 2015 (line 383-384) -> They measured fitness as reproductive effort (realized value relative to what would be expected given body size). -> we concluded this is okay because of how they measure fitness
- [x] #Green & Hatchwell 2018 (line 465) -> authors calculated this and sent us the mean and SD, all other calculations aren't flagged. Note this is indirect fitness, so this spread isn't crazy. -> we concluded this is okay
- [x] #Qu et al. 2018 (line 458-459) -> extracted from figure using an estimated n -> we concluded this is okay
- [x] #Spence-Jones et al. 2021 (line 662-663) -> data extracted from figure -> we concluded this is ok
- **sanity checks - sd/proportion or sd/percentage above 4**
- [ ] #Small et al. 1993 (line 141-144) -> estimated n and converted 95% CIs to SD (table 2 page 2023) -> keep the composite because sample size overall is 
- [ ] #Orell et al. 1999 (line 544 & 549) -> converted SE to SD (text page 290) -> we concluded this is okay
- [ ] #Spence-Jones et al. 2021 (line 661) -> converted SE to SD (text page 241) -> we concluded this is okay
- [ ] #Brown et al. 2008 (line 293-294) -> extracted from figure (figure 1 page 8) -> we concluded this is okay
- [ ] #Devillard & Bray 2009 (line 308-309) -> extracted from figure (figure 1 page 2908) -> we concluded this is okay

**Comment by martinig** [comment]
@mlagisz 
- [x] cross check records that are marked as "yes" in the "needs_another_opinion" column ([link](https://docs.google.com/spreadsheets/d/1ZWQUCG5wuLIPJbhYfRW_rvFVb4qFiWtFm2e0BZ5WBkE/edit?usp=sharing) to dataset)

**Comment by martinig** [comment]
@Yefeng0920 

- [ ] resolve error: VCV matrix (SN is looking into this)
- [ ] resolve error: effect size direction
- [ ] spp figure
- [ ] sent ARM spp names for significant spp so that ARM can find silhouettes
- [ ] leave one species out analysis
